name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout church-connect
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Clone joshmacaraig.github.io
        uses: actions/checkout@v3
        with:
          repository: joshmacaraig/joshmacaraig.github.io
          ref: gh-pages
          path: main-site
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Create church-connect directory
        run: |
          mkdir -p main-site/church-connect
          cp -r dist/* main-site/church-connect/
      - name: Deploy to joshmacaraig.github.io
        uses: peaceiris/actions-gh-pages@v3
        with:
          repository: joshmacaraig/joshmacaraig.github.io
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./main-site
          publish_branch: gh-pages
